### ISSUE TITLE
why we should require nats?

### ISSUE THREAD

**Issue by amir-yaghoubi** [hemerajs/hemera-rabbitmq#1]
Hi, as u mentioned in your example we need to require nats and connect to it.
```
const Hemera = require('nats-hemera')
const nats = require('nats').connect()
```
My question is why we needs to provide nats when we want to connect via rabbitMQ?

**Comment by StarpTech** [comment]
Hi @amir-yaghoobi,
hemera always communicates over NATS. Hemera-rabbitmq provides a bridge to receive and send messages over RabbitMQ.

**Comment by StarpTech** [comment]
Feel free to reopen if you have any questions.
